### PR TITLE
Rosepine Theme

### PR DESCRIPTION
**Pull request by bw8686**
# Rosepine Theme

https://github.com/rose-pine/steam-os Themes steamos pretty simple.

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 10MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.

Check one box.
- [x] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [ ] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [x] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [ ] This theme does not target the keyboard.

### CODE REVIEW

**Comment by EMERALD0874** [comment]
At least one syntax error that can be found with [The W3C CSS Validation Service](https://jigsaw.w3.org/css-validator/validator).

It is becoming increasingly clear that you are not using any sort of consistent code formatting, syntax checker, or peer-reviewing beyond the reviewers of this repository. We should be the last line of defense when it comes to bugs and other issues. I recommend taking the following steps moving forward:

1. Install Visual Studio Code or another IDE. Extensions like Prettier will help you maintain consistent code formatting, making it easier for peers to review your code.
2. Use a syntax checker like [The W3C CSS Validation Service](https://jigsaw.w3.org/css-validator/validator). This will save us a lot of time finding smaller errors in your code that could be found much more easily on your own.

We are using our free time to test your theme. Please use these tools to review your code before making another commit.

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
Syntax errors on line 61 of each keyboard theme.

**Comment by bw8686** [comment]
1. i dont care and im pretty sure i have it installed
2. fuck you visual code studio i was  damn sure i fixed all syntax errors#
3. gimme a second and ill fucking fix it

**Comment by bw8686** [comment]
fixeddddddddddddddddddddddddddd

**Comment by EMERALD0874** [comment]
You have been highly disrespectful to me and the other contributors to this repository. Wasting our time and saying "I don't care" with multiple swears in response to us asking you to check your work is extremely infuriating. Additionally, your code ***still*** has errors. It is clear you have no respect for us or our time.

image

This pull request is being closed. We will not be reviewing any more pull requests regarding this theme unless you have a collaborator format and syntax check your code so it is functional and legible by our reviewers. **Do not create another pull request for Rosepine until you have done this.**

**Pull request closed without merging**
