### PR TITLE
added requisite files for the DeckText theme to be added to the db.

### PR DESCRIPTION
**Pull request by mmatis**
# DeckText

URL: https://github.com/mmatis/DeckText

A theme that bumps up the size of the Steam Deck's UI text and some controls, making it easier to read and more accessible for people with diverse needs. 

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 4MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [x] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [ ] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [x] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [ ] This theme does not target the keyboard.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
You seem to have left out your theme name and a link to your theme repository?

**Comment by mmatis** [comment]
Apologies! Updated the merge comment. I knew I'd miss something!

**Review by suchmememanyskill — APPROVED** [review]
Only noticed 1 slight issue: in the theme.json, line 18, "Main Manu" is misspelt. Do you want to fix this or should i merge it?

**Comment by suchmememanyskill** [comment]
Is it ready to merge now?

**Comment by mmatis** [comment]
I fixed the typo in my repo and attempted to update the commit in my author .json to 15caeb5. Is there anything else I need to do? If not, then I think it's ready.

**Comment by suchmememanyskill** [comment]
I'm waiting until the CI test builds your theme, but it's taking a while for some reason. Nothing should be required from your side

**Pull request merged**
