### PR TITLE
Adding Animated synthwave theme

### PR DESCRIPTION
**Pull request by konqiDAM**
# Animated Synthwave

https://github.com/konqiDAM/Simple-deck-themes

Name: SynthwaveTheme
Description: Animated backgrounds for library, home and keyboard. Also option to set transparency of keyboard to enjoy more the animation. 

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 10MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [ ] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [x] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [x] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [ ] This theme does not target the keyboard.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
CI failed. You provided an invalid repository url

**Comment by konqiDAM** [comment]
updated the theme, think should be fine now

**Comment by konqiDAM** [comment]
updated again sorry, but last time today haha

**Comment by konqiDAM** [comment]
wops, pushed another theme and didn't notice it would be added to this pull request. Its another theme only aimed to keyboard. Do I revert or something?

**Review by EMERALD0874 — DISMISSED** [review]
> Exception: Patch 'Amount green primary keys' contains css that does not exist

Also, I recommend waiting until the color picker is released before releasing this theme. It should make navigation significantly easier and require one file instead of many.

**Comment by konqiDAM** [comment]
ok reverted it

**Review by beebls — APPROVED** [review]
Everything works on v1.1.0, but once the next update comes out, maybe consider moving some things to the color picker component to make it easier on yourself.

**Comment by konqiDAM** [comment]
Ok thanks, but do you mean the synthwave theme or the custom keyboard with rgb selector?

**Pull request merged**
