### PR TITLE
Wii Theme

### PR DESCRIPTION
**Pull request by OT-Archmage**
# Wii Theme

[Insert a link to the GitHub repository of the theme and describe the major changes your theme makes here.](https://github.com/OT-Archmage/SteamDeckCustomisations/tree/main/CSS%20Themes/Wii%20Theme)

- Changes the home screen to look more like the Wii's Menu
- Updates the side menus to look like the Wii's Home Menu
- Makes the Game Details page fullscreen and changes the buttons
- Updates the settings menu to look more like the Wii's settings interface

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 10MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [x] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [ ] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [ ] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [x] This theme does not target the keyboard.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
Some personal notes on this theme:

- The CSS variables are not prefixed with a unique indentifier
- Line 234 and 289 contains a `*`, please refrain from using `*`'s
- Line 141 and 274 contain syntax errors
- Styling across the css file is inconsistent

Please fix these points

**Comment by OT-Archmage** [comment]
Could you elaborate on that last point about styling being inconsistent? Do you mean the way the file is formatted or the way the theme itself looks?

**Comment by suchmememanyskill** [comment]
How the file is formatted. As an example:
```
/*Applies to All*/
* {
	font-family: "Noto Sans" !important; }

/*Tab Group*/
.gamepadtabbedpage_FixCenterAlignScroll_1CJeU.scrollpanel_ScrollPanel_1CXdi.scrollpanel_ScrollX_1oRGo{
	gap: 20px;
	background-color: 0%;
}


.basicappdetailssectionstyler_AppDetailsContainer_2-ns_ .gamepadtabbedpage_GamepadTabbedPage_3IBLc .gamepadtabbedpage_TabContents_WDa0_ {
    background-image: var(--IMG_SettingsBG);
}
```
The brackets here all have different ways they're written

**Comment by suchmememanyskill** [comment]
https://github.com/OT-Archmage/SteamDeckCustomisations/blob/main/CSS%20Themes/Wii%20Theme/shared.css#L249
https://github.com/suchmememanyskill/Steam-Deck-Themes/blob/137024bea7a324829bc9c9e278dfa9056d8380a4/Clean%20Gameview/shared.css

You have checked the following box: `I am not bundling a part of another theme with this theme to encourage mixing and matching themes.`. This is seemingly not correct as you are bundling clean gameview

**Comment by suchmememanyskill** [comment]
Hi, would you mind stripping out the switch like home theme and using theme dependencies to add it back? (New feature introduced 3 hours ago)

Also, you can now load images locally, may also want to use that

**Comment by OT-Archmage** [comment]
Hi, sorry I wasn't able to respond sooner as I was away.

I don't have any elements of Switch-Like Home in this theme, we use different methods of moving the tabbed content that aren't interchangeable. If you're talking about Clean Gameview, I'll replace it with a dependency.

**Comment by OT-Archmage** [comment]
I've just pushed an update based on your previous comments, let me know if there's anything else you need me to change!

**Review by suchmememanyskill — APPROVED** [review]

**Pull request merged**
