### PR TITLE
Chiaki Nanami Theme Contribution

### PR DESCRIPTION
**Pull request by Dutchsnake5**
# Chiaki Nanami Theme 

https://github.com/Dutchsnake5/Steam-Deck-Themes-By-Five

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 10MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [ ] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [x] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [ ] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [x] This theme does not target the keyboard.

This request is to add my own theme. I have a toggle feature for a Switch-Like home menu, and the code used was derived from EMERALD's work, and the artwork is by CiloRanko

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
Your repo reference .json contains syntax errors.

Also, you're including the "switch like home" theme, but you don't seem to be linking back to the source repository for this

**Comment by Dutchsnake5** [comment]
Haha I can't believe I forgot to .json verify the author json file, my bad! As for the Switch-Like theme, I adapted it from joamjoamjoam's findings, but changed the `top-margin` value. I will add his source repo in the README.md and the .json

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
Theme improperly credits "joamjoamjoam" as the creator of the Switch-Like Home theme. Please change this to "suchmememanyskill" or remove the attribution entirely (which is allowed under the MIT License) as this violates his copyright.

**Comment by Dutchsnake5** [comment]
Changed. Sorry for the confusion

**Review by suchmememanyskill — CHANGES_REQUESTED** [review]
In Image.css, at the end of line 2, there is a syntax error. Please fix

Other than that, looks good

**Comment by Dutchsnake5** [comment]
Fixed. It was hard to see the syntax error due to how long the image data is haha

**Review by suchmememanyskill — APPROVED** [review]

**Pull request merged**
