### PR TITLE
Added HideHomePlaytime SP-theme

### PR DESCRIPTION
**Pull request by BananaAcid**
# Hide Home Playtime

Insert a link to the GitHub repository of the theme and describe the major changes your theme makes here:

[Hide Home Playtime Repo](https://github.com/BananaAcid/SteamDeck-CSS-Themes/tree/main/themes/HideHomePlaytime)

Hides or fades the last played text (often showing "Not playtime yet") on the home screen, has an option to hide the title "Recent Games" and an extra option to push the caption and the last played text a few pixels to the right in case of a missalignment caused by some themes.

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 4MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [x] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [ ] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [ ] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [x] This theme does not target the keyboard.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
Isn't this theme exactly the same as `Hide Play Time` currently available on the store?

**Comment by BananaAcid** [comment]
> Isn't this theme exactly the same as `Hide Play Time` currently available on the store?

It hides it in the homescreen / startpage instead / only there. Game pages can still list the page - there you would use `Hide Play Time`.

**Comment by suchmememanyskill** [comment]
There was an update 18 hours ago on the theme to update it to hide it on the home screen as well. Please double check

**Comment by BananaAcid** [comment]
> There was an update 18 hours ago on the theme to update it to hide it on the home screen as well. Please double check

This one only does the homescreen, not the game screens. as well as removes the title.

**Comment by suchmememanyskill** [comment]
Again, please double check the theme. You'll see what i mean

**Comment by BananaAcid** [comment]
> Again, please double check the theme. You'll see what i mean

Just checked it. Has an option to hide it (toggle) but not to set the alpha in different steps as mine does. And has no option to hide the title. 🤷‍♂️ As well as removes the whole info block by their plugin, not only the last played part (it seems so at least).

**Comment by BananaAcid** [comment]
@suchmememanyskill  so do you feel it is obsolete or do you have any suggestions?

**Comment by suchmememanyskill** [comment]
I have brought it up with the rest of the team, personally i think it conflicts with an already existing theme. You could get in touch with them to merge your changes

**Comment by beebls** [comment]
Closing as this does the same function as another theme.
If you would like to have the alpha/title functionality, please PR it to the existing Hide Play Time theme, having duplicates isn't great for the user.

**Pull request closed without merging**
