### PR TITLE
AlternativeLockScreen

### PR DESCRIPTION
**Pull request by ghost**
**AlternativeLockScreen**

[My link to the source code](https://github.com/SudoTheHacker/Steam-Deck-Themes/tree/main/AlternativeLockScreen)
It's basically a different locking lock screen without feeling like it's a completely different experience. It would be the very first theme for lock screen which look "normal" compared to the simple lock screen which is not even centered

**### Checklist**

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 4MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [x] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [ ] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [ ] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [x] This theme does not target the keyboard.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
CI failed to validate the theme. your preview image path is invalid

**Comment by ghost** [comment]
Fixed it

**Comment by ghost** [comment]
Should be fixed and if it dosen't work, I do not understand what's the problem

**Comment by suchmememanyskill** [comment]
Please refrain from making this many commits, it's annoying to keep track of. Clone it to your pc and work from it there

CI validation failed. Commit `c831aad` does not exist in your remote repository. `1e5bca7` is your latest commit

**Comment by ghost** [comment]
Sorry, so do I just put the latest commit (which is e306d45) in the document.

**Comment by suchmememanyskill** [comment]
that's the latest commit in your themedb fork. It needs to be a commit (latest?) in the repository where your theme is stored

**Comment by ghost** [comment]
Oh okay, that's my bad, I must have read the instruction wrong.

**Comment by suchmememanyskill** [comment]
If you can't figure it out i made a discord bot for theme submissions where you upload your theme as a zip and it makes a valid pull request for you. May be easier

**Comment by suchmememanyskill** [comment]
CI Passed, will review later

**Comment by suchmememanyskill** [comment]
image
is it supposed to look like this? It doesn't look like your screenshot

**Comment by ghost** [comment]
This is the old version. It would be fixed by now.

**Comment by suchmememanyskill** [comment]
I tested the build generated by the CI, which is what will be submitted to the theme db. https://github.com/suchmememanyskill/CssLoader-ThemeDb/actions/runs/3221404048

**Comment by My1** [comment]
considering there has been an update with the lockscreen a new look onto everything is recommended

**Comment by ghost** [comment]
Unfortunately, I do not have my steam deck anymore. I would recommend not trying to work on this theme anymore. I’ll try to see if I can end this pull request.

**Pull request closed without merging**
