### PR TITLE
Adding Gawr Gura Theme

### PR DESCRIPTION
**Pull request by joamjoamjoam**
# Gawr Gura and Proton DB Badges Themer

[ Proton DB Badges Themer](https://github.com/joamjoamjoam/SteamDeckThemes/blob/main/ProtonDB_Badges)
[Gawr Gura](https://github.com/joamjoamjoam/SteamDeckThemes/tree/main/Gawr%20Gura)

Proton DB Badges Themer Major Changes:
- Only themes the added protonDB medal from OMGDukes plugin. 
- Bundles Clean Game View and enables it when the user selects an option that uses it.

Gawr Gura Major Changes:
- Purely a reskin of most of the deck UI Elements
- Changes colors of the Header, Footer, QAM, and Steam Menu 
- rearranges lockscreen UI to accommodate the picture. (moved to bottom right corner)
- Skins the default keyboard if the user chooses to.
- Adds Pictures (Local Base 64) to the LockScreen, Main Screen, Library, and Keyboard skins (if selected).
- Keyboard Skins skin basically everything, keys, glyphs, emoji screen

Configurable options include:
- 2 keyboard skins and None option
- Enable/Disable No Friends on home screen
- Enable/Disable Colored Toggles with a custom gradient
- Enable/Disable Clean Game View

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 10MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [ ] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [x] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [x] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [ ] This theme does not target the keyboard.

### CODE REVIEW

**Comment by EMERALD0874** [comment]
@joamjoamjoam - Please complete the template by adding the theme names and major changes as requested above. I also need to discuss whether or not READMEs should be allowed in theme folders with @suchmememanyskill as the current checks do not allow them.

**Comment by EMERALD0874** [comment]
When we say "the major changes your theme makes," we are asking you to describe what changes your theme makes to the Steam Deck UI. We understand this is a new theme, but we are trying to have a basic understanding of your theme and know what we need to check.

Please update your PR description.

**Comment by joamjoamjoam** [comment]
Sorry for that I completely missed those placeholders. As for the READMEs , I think its a good idea to have them per theme because as you build a theme repo the root level readme would  be cluttered. As a theme user I've gone to a repo to check out a theme and there is no pictures or descriptions other than "My Deck Theme Repo". Maybe the store download could delete the readme or something.

**Comment by joamjoamjoam** [comment]
Related to the README stuff it would be nice if there was a requirement to have a description and preferably more pictures in the repository that houses the theme that explains what the theme does. Some themes changes are hard to see with just one picture and navigating to the repo usually doesn't help since there is no description or pictures there either.

I guess maybe even a required description field in the json files in this repo that shows on the store page would be sufficient.

**Comment by EMERALD0874** [comment]
If you'd like to create issues for those as feature recommendations, we can definitely look into that. An issue about allowing READMEs in theme folders would actually be very helpful for me to send to the other plugin authors.

I'll go ahead and review your themes in a little bit, but I already see some things I'll want to be changed. Also, could you please answer these questions so I can gain a little insight into why you chose to make the ProtonDB Badges theme? We're considering whether we should allow this as a theme or defer your changes to the plugin itself.

1. Do you consider the transparency on hover change to be an overall improvement or an option the user should have?
1. Is there any particular reason you chose to make these changes in a theme rather than a ProtonDB Badges plugin issue/PR?

**Comment by joamjoamjoam** [comment]
Good idea I created issue #54 for the README.

For the proton plugin:
I created the issues tracking both 1 and 2 on the actual plugin itself. The reason I still decided to try to publish the theme is provide an example for theming these medals and more importantly to make it known that these medals (which by Decky Loader design share the same classes as any DialogButton) are affected by any System-Wide theme that styles the Dialog Button.

I'm not too worried about the protonDB plugin if you decide to reject it but it might be useful knowledge that generically theming the Dialog Button class on the SP tab may cause unintended issues into the future.

For quick reference here's the classes of the protonDB Medal created using the Decky Loader DialogButton static class. There's also no Requirement from Decky to uniquely class or id a DialogButton.

`<button type="button" class="protondb-decky-indicator DialogButton _DialogLayout Secondary gamepaddialog_Button_1kn70 Focusable" tabindex="0" style="top: 40px; left: 20px; position: absolute; background: rgb(207, 181, 59); z-index: 20; color: black; padding: 8px; display: flex; align-items: center; width: max-content;">ProtonDB Logo<span style="margin-left: 10px; font-size: 20px;">Gold</span></button>`

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
If you want to get this out the door immediately, please remove the README files from the theme directories and make the changes below. If you want to wait for the README issue to be resolved, feel free to leave them until that happens.

- The Proton DB Badges Themer is denied. The changes you have made are already implemented or planned in the plugin itself.
- Switch-Like Home is enforced and should be an option or not included. Users may or may not want the recent game wallpaper to be more visible.
- Please consider updating your theme to use the [new patch types](https://github.com/suchmememanyskill/CssLoader-ThemeDb#upgrading-a-theme) since you are using multiple yes/no options.
- Holding down a letter on the keyboard uses confusing colors (the blue is transparent making the letter hard to see and the red contrasts greatly from the rest of the keyboard).
- Your lock screen modifications remove the button prompts on each key and creates accessibility concerns. Please consider making this a separate theme.
- Your lock screen movement overlaps with the button prompt footer. Please move this up slightly to avoid blocking the buttons or find a way to move it behind the footer.

**Comment by suchmememanyskill** [comment]
Please rebase this PR. This should fix the readme issue

**Comment by joamjoamjoam** [comment]
1. Yup not a problem all the issues mentioned above were fixed in the plugin itself.
2. Forgot about that one. it now uses a patch
3. Update patches to use the new patch types.
4. That was unintended. I updated the keyboard themes to use the right colors. 
5. Added a minimal lock screen theme with the button prompts and allow the lock screen to be disabled completely. I'm going to submit the lock screen as a separate theme later today.
6. Oh Wow how did I miss that? Fixed.

**Comment by joamjoamjoam** [comment]
Branch is up to date with Readme changes.

**Comment by suchmememanyskill** [comment]
CI Failed. `Exception: A v2 Patch was detected but a v1 manifest was provided`

**Comment by joamjoamjoam** [comment]
Corrected Manifest version to v2.

**Review by EMERALD0874 — APPROVED** [review]

**Review by EMERALD0874 — CHANGES_REQUESTED** [review]
- Please make "Minimal with Icons" the default lock screen theme for the accessibility reasons previously discussed.
- Switch Like Home and No Friends options conflict. Please make one dropdown that switches between "no, yes with friends, yes without friends" (or something similar) or resolve the conflict. You can observe this by having Switch Like Home on but No Friends off.
- (Optional) You may want to consider turning Colored Toggles into a checkbox due to it being a yes/no patch.

**Comment by joamjoamjoam** [comment]
I left the Colored Toggles options as a drop down because I might as some more colors in the future.

**Review by EMERALD0874 — APPROVED** [review]
LGTM

**Pull request merged**
