### PR TITLE
Fix code issues and standardize code

### PR DESCRIPTION
**Pull request by neodark**
This fixes coding issues (such as false comparison with "!=None", etc.) and I added standardized the code with black, isort, etc.

I also added pre-commit hooks to improve the code standardization

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
Could you please message me on discord? I want to discuss the implementation of this

**Comment by neodark** [comment]
Sure, what's your discord channel?

**Comment by suchmememanyskill** [comment]
The decky discord is in the readme but i also have a [personal dev discord](https://discord.gg/aH9rsuP)

**Comment by EMERALD0874** [comment]
Closing this due to inactivity. Please feel free to reach out to @suchmememanyskill on Discord if you want to continue work on this PR.

**Pull request closed without merging**
