### PR TITLE
Rounded Keyboard

### PR DESCRIPTION
**Pull request by Ian-Boraks**
# Rounded Keyboard

[Link to github repository of Rounded Keyboard](https://github.com/Ian-Boraks/SteamDeck-CSS-Themes/tree/main/RoundedKeyboard)

## Checklist:

- [X] I am the original author of this theme.
- [X] I am not bundling a part of another theme with my theme (or are making it optional with patches), to encourage mixing and matching themes
- [X] I marked my theme target appropriately, and made sure my theme only themes the part it says it does
    - [X] If this is a keyboard theme, this theme gets applied to the default keyboard :)
    - ~~[ ] If this is a System-Wide theme, this theme does not bundle a keyboard theme (or are making it optional with patches)~~
- [X] I have verified that my theme works properly on the latest versions of SteamOS, decky-loader and SDH-CssLoader.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
Traceback (most recent call last):
  File "main.py", line 348, in <module>
    reference.verify()
  File "main.py", line 135, in verify
    raise Exception("Image does not exist in repo")
Exception: Image does not exist in repo

Please don't add a leading `/` for the path

**Comment by suchmememanyskill** [comment]
image
Looking at the css, what is this * doing here?

**Comment by Ian-Boraks** [comment]
Let me remove the star and update the "preview_image_path". That star was used to grab every child element of that class.

Replaced the `*` with `.virtualkeyboard_KeyboardExtendedKey_394j7` and it seems to be working.

**Review by suchmememanyskill — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
