### PR TITLE
Submit theme Clean UI.

### PR DESCRIPTION
**Pull request by apognu**
# Clean UI

[apognu/steamdeck-clean-ui](https://github.com/apognu/steamdeck-clean-ui)

Subtle improvements to style and consistency across the Steam Deck's UI.

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 4MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [x] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [ ] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [x] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [ ] This theme does not target the keyboard.

### CODE REVIEW

**Review by suchmememanyskill — CHANGES_REQUESTED** [review]
- `apognu-CleanUI.json` contains an invalid repo subpath
- You have checked the option `This is a keyboard theme applied to the default keyboard.`. Your theme is marked as a `System-Wide` theme, thus the keyboard edits need to be toggleable. 
- `release.json` in your theme repository is unnesesary. It only affects items placed in your repo subpath folder

**Comment by apognu** [comment]
I've performed the necessary changes.

**Review by suchmememanyskill — CHANGES_REQUESTED** [review]
Keyboard is still affected (and completely broken for me, it's skipping rows). Please test your theme before submission

**Comment by suchmememanyskill** [comment]
image
seems to be caused by this

**Comment by apognu** [comment]
Right, missed that, the fix for this is now in the patch. I'll make sure the keyboard is untouched, and submit again.

**Comment by EMERALD0874** [comment]
Closing this due to inactivity. Please feel free to create a new PR once you've made the changes.

**Pull request closed without merging**
