### PR TITLE
Rosepine Theme

### PR DESCRIPTION
**Pull request by bw8686**
# Rosepine Theme

https://github.com/rose-pine/steam-os

## Checklist:

- [x] I am the original author of this theme.
- [x] I am not bundling a part of another theme with my theme, to encourage mixing and matching themes
- [x] I marked my theme target appropriately, and made sure my theme only themes the part it says it does
    - [x] If this is a keyboard theme, this theme gets applied to the default keyboard
- [x] I have verified that my theme works properly on the latest versions of SteamOS, decky-loader and SDH-CssLoader.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
Pull request does not follow the template

Theme does not follow the file structure that is expected. Will not merge until fixed

Also from a quick peek at the theme.json you don't specify a target. This is required

**Comment by bw8686** [comment]
fixed

**Comment by suchmememanyskill** [comment]
Exception: Theme has no author

Please read trough the entire readme and see if you have everything

**Review by suchmememanyskill — CHANGES_REQUESTED** [review]
All .css files contain at least 1 syntax error. Please fix

**Pull request closed without merging**
