### PR TITLE
Update for other default themes

### PR DESCRIPTION
**Pull request by Wormss9**
# Insert Theme Name(s) Here

https://github.com/Wormss9/SteamDeckThemes

Adding [missing]https://github.com/Wormss9/SteamDeckThemes/issues/1 default skins

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 4MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [x] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [ ] Themes included with this theme are toggleable using a patch.

Check one box.
- [x] This is a keyboard theme applied to the default keyboard.
- [ ] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [ ] This theme does not target the keyboard.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
You checked `This is a keyboard theme applied to the default keyboard`. It also applies to other keyboards. We disallow keyboard themes that target more than the default keyboard

**Comment by EMERALD0874** [comment]
I think this might be a special case since it doesn't really modify the keyboard outright, just makes the content behind it more visible. This could be considered more of an accessibility feature than a keyboard modification, but just my thoughts.

**Comment by james2432** [comment]
I agree with EMERALD0874 this is just affecting the transparency for all the steam provided keyboards, which in MMOs and typing in terminals is almost needed as you cannot see what you are doing.

Restricting to default theme for keyboard restricts everyone to the default keyboard, which doesn't look as good as others

**Comment by suchmememanyskill** [comment]
Maybe an exception can be made then

My main concern is that i do not want any theme to mess with valve's official keyboard themes.

Then last one thing with this PR: The css is a giant copy paste mess. it doesn't seem like a great idea to implement it like this

**Comment by Wormss9** [comment]
I made a [script](https://github.com/Wormss9/SteamDeckThemes/blob/main/colorGenerator.js) for it. I tried to move the shared code to shared.css and use variables but it didn't work. How could I implement it better?

The cleanest solution would be to just override the color opacity but `--color: rgb(var(--color)/ var(--opacity))` just makes it transparent.

**Review by EMERALD0874 — APPROVED** [review]
LGTM. Approving this since nobody has been able to optimize the code in the way @suchmememanyskill mentioned.

**Pull request merged**
