### PR TITLE
Pretendo Theme

### PR DESCRIPTION
**Pull request by DirectorReiuji**
# Pretendo Theme

[Pretendo Theme Repository](https://github.com/CirnoMoment/Cirno-Steam-Deck-Themes/tree/main/Pretendo)

Based on the Nintendo Network replacement, Pretendo, this theme changes the background to the logo and mascot, while also changing the system's color pallette to Pretendo colors. These changes are reflected within the main menu, home menu, navigation, and more.

### Checklist

Failure to complete this checklist or deleting boxes from the checklist will result in the closing of your pull request unless this is a theme update. Please write any comments regarding this checklist at the bottom of your pull request.

Check every box.
- [x] I am the original author of this theme or have permission from the original author to make this pull request.
- [x] All copyright of this theme's contents belong to the listed author or is cited in the repository linked above.
- [x] This theme's target has been marked appropriately and only styles said target.
- [x] This theme works properly on the latest versions of SteamOS for Steam Deck, [decky-loader](https://github.com/SteamDeckHomebrew/decky-loader) and [SDH-CssLoader](https://github.com/suchmememanyskill/SDH-CssLoader).
- [x] This theme only uses `*` or `!important` if absolutely necessary.
- [x] This theme is under 4MB in size and uses the least disk space possible.
- [x] This theme's preview image does not include text unless it is necessary to describe changes that can be made.
- [x] This theme is safe for work and does not contain any sexual, drug-related, or profane content.
- [x] This theme prefixes any CSS variables with a unique identifier.

Check one box.
- [ ] I am not bundling a part of another theme with this theme to encourage mixing and matching themes.
- [x] Themes included with this theme are toggleable using a patch.

Check one box.
- [ ] This is a keyboard theme applied to the default keyboard.
- [ ] This is a system-wide theme applied to the default keyboard. The keyboard is toggleable using a patch.
- [x] This theme does not target the keyboard.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
Don't know if you noticed, but this theme failed to validate. You seem to have added the theme user configuration to the theme itself

**Comment by DirectorReiuji** [comment]
Yup, noticed it now, should hopefully be fixed now.

**Comment by suchmememanyskill** [comment]
Alright, on reviewing the theme it looks like you are bundling other themes. This is fine, but may be annoying to maintain. Would you be up for changing your bundled themes to [dependencies](https://github.com/suchmememanyskill/CssLoader-ThemeDb#theme-dependencies)? Dependencies basically download the latest version of specified themes, and enable them alongside your theme

It seems like you are using the following themes:
- Round
- Obsidian
- Switch Like Home
- An old version of Colored Toggles(?)

If you don't want to switch over to dependencies, each theme you included should be toggleable

You can also host images locally, if you prefer

**Comment by DirectorReiuji** [comment]
So I looked into it, and I could do that for Round and SLH, however I did not use Colored Toggles, instead I configured the text and toggles on my own. Now it should be able to essentially look like an Obsidian reskin with more color pallete changes.

**Comment by suchmememanyskill** [comment]
Ah alright. Looking at the way you implemented dependencies, is it intended that you don't set a specific value for the patches of rounded? If you don't set a value it'll take whatever the user set last (or the default, if the user never enabled the theme before)

**Comment by suchmememanyskill** [comment]
The CI validation failed as your theme.json is marked as a v1 manifest. Add `"manifest_version": 3` to the theme.json

**Comment by DirectorReiuji** [comment]
Yup, just upgraded it now.

**Review by suchmememanyskill — APPROVED** [review]

**Comment by suchmememanyskill** [comment]
Ready to merge?

**Review by suchmememanyskill — CHANGES_REQUESTED** [review]
oh wait, i missed something: your css variables in shared.css are not prefixed with an unique identifier

**Comment by DirectorReiuji** [comment]
So I should make the variables unique in name? Alright that's easy.

**Comment by suchmememanyskill** [comment]
re-testing the theme i noticed another thing, for me when using the pretendo theme the images on the home menu are square, while the selection box is rounded. The base rounded theme does not have this issue. Are you accidentally modifying that?

You also seem to be overriding other elements of rounded in general

**Comment by DirectorReiuji** [comment]
Yeah I just realized that since I used Round as a base for the share.css, there's some leftover code, I'll be quickly removing that and that should fix up that issue.

**Comment by DirectorReiuji** [comment]
Alright I tested it out and that bug should be fixed.

**Comment by suchmememanyskill** [comment]
you seem to have reverted image.css in the process, it's css variable is no longer uniquely prefixed

**Comment by DirectorReiuji** [comment]
Yeah... Forgot about that, now the unique prefix should be back there.

**Review by suchmememanyskill — APPROVED** [review]
Ready to merge?

**Comment by DirectorReiuji** [comment]
Yes.

**Pull request merged**
